---
- name: Setup Game Assets
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

  - name: Create ./tmp
    ansible.builtin.file:
      path: ./tmp
      state: directory
      mode: '0755'

  - name: Download Kenney Fonts (https://kenney.nl/media/pages/assets/kenney-fonts/1876150b34-1677661710/kenney_kenney-fonts.zip)
    ansible.builtin.get_url:
      url: https://kenney.nl/media/pages/assets/kenney-fonts/1876150b34-1677661710/kenney_kenney-fonts.zip
      dest: ./tmp/kenney_kenney-fonts.zip
      checksum: sha256:4e69a86eef3cd47e9d8207413868cd08bcddeb2dae4047dbd10362e2a7a16bac

  - name: Create ./tmp/kenney-fonts/
    ansible.builtin.file:
      path: ./tmp/kenney-fonts/
      state: directory
      mode: '0755'

  - name: Unzip kenney_kenney-fonts.zip to ./tmp/kenny-fonts/
    ansible.builtin.unarchive:
      src: ./tmp/kenney_kenney-fonts.zip
      dest: ./tmp/kenney-fonts/

  - name: Create the ../fonts/ directory for the game
    ansible.builtin.file:
      path: ../fonts/
      state: directory
      mode: '0755'

  - name: Copy fonts from ./tmp/kenney-fonts/Fonts/* to ../fonts
    ansible.builtin.copy:
      remote_src: true
      src: "{{ item }}"
      dest: ../fonts/
    with_fileglob:
      - "./tmp/kenney-fonts/Fonts/*"

  - name: Download Kenney Input Prompts Pixel 16 (https://kenney.nl/media/pages/assets/input-prompts-pixel-16/a9d5de5009-1677495570/kenney_input-prompts-pixel-16.zip)
    ansible.builtin.get_url:
      url: https://kenney.nl/media/pages/assets/input-prompts-pixel-16/a9d5de5009-1677495570/kenney_input-prompts-pixel-16.zip
      dest: ./tmp/kenney_input-prompts-pixel-16.zip
      checksum: sha256:b0b41fc4d2681698a6002914daabf2a1a69050fde87d2bf96de7f43b025b7df6

  - name: Create ./tmp/input-prompts/
    ansible.builtin.file:
      path: ./tmp/input-prompts/
      state: directory
      mode: '0755'

  - name: Unzip kenney_input-prompts-pixel-16.zip to ./tmp/input-prompts/
    ansible.builtin.unarchive:
      src: ./tmp/kenney_input-prompts-pixel-16.zip
      dest: ./tmp/input-prompts/

  - name: Create the ../sprites/input-prompts/pixel-16/ directory for the game
    ansible.builtin.file:
      path: ../sprites/input-prompts/pixel-16/
      state: directory
      mode: '0755'

  - name: Copy tilemap_packed.png to ../sprites/input-prompts/pixel-16/
    ansible.builtin.copy:
      remote_src: true
      src: "./tmp/input-prompts/Tilemap/tilemap_packed.png"
      dest: ../sprites/input-prompts/pixel-16/

  - name: Download Kenney Pixel SHMUP (https://kenney.nl/media/pages/assets/pixel-shmup/899a89fc6e-1677495782/kenney_pixel-shmup.zip)
    ansible.builtin.get_url:
      url: https://kenney.nl/media/pages/assets/pixel-shmup/899a89fc6e-1677495782/kenney_pixel-shmup.zip
      dest: ./tmp/kenney_pixel-shmup.zip
      checksum: sha256:e33fd626b799de343f18c81ebaa6f3bc161772fdd717acf3f223589ce74cf952

  - name: Create ./tmp/pixel-shmup/
    ansible.builtin.file:
      path: ./tmp/pixel-shmup/
      state: directory
      mode: '0755'

  - name: Unzip kenney_pixel-shmup.zip to ./tmp/pixel-shmup/
    ansible.builtin.unarchive:
      src: ./tmp/kenney_pixel-shmup.zip
      dest: ./tmp/pixel-shmup/

  - name: Create ../sprites/pixel-shmup/ directory for the game
    ansible.builtin.file:
      path: ../sprites/pixel-shmup/
      state: directory
      mode: '0755'

  - name: Copy packed tilemaps from ./tmp/pixel-shmup/Tilemap/*_packed.png to ../sprites/pixel-shmup/
    ansible.builtin.copy:
      remote_src: true
      src: "{{ item }}"
      dest: ../sprites/pixel-shmup/
    with_fileglob:
      - "./tmp/pixel-shmup/Tilemap/*_packed.png"

  - name: Create ../sprites/pixel-shmup/
    ansible.builtin.file:
      path: ../sprites/pixel-shmup/
      state: directory
      mode: '0755'

  - name: Create ../sprites/input-prompts/pixel-16/
    ansible.builtin.file:
      path: ../sprites/input-prompts/pixel-16/
      state: directory
      mode: '0755'

  - name: Copy tile sheet maps ships_sheet.xml
    ansible.builtin.copy:
      remote_src: true
      src: "../etc/ships_sheet.xml"
      dest: "../sprites/pixel-shmup/ships_sheet.xml"

  - name: Copy tile sheet maps tilemap_sheet.xml
    ansible.builtin.copy:
      remote_src: true
      src: "../etc/tilemap_sheet.xml"
      dest: "../sprites/input-prompts/pixel-16/tilemap_sheet.xml"

  - name: Copy tile sheet maps tiles_sheet.xml
    ansible.builtin.copy:
      remote_src: true
      src: "../etc/tiles_sheet.xml"
      dest: "../sprites/pixel-shmup/tiles_sheet.xml"